name: Deploy web on push
on: 
  push:
    branches:
    - master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action
      with: 
        server: ftp.bengkelsehati.id
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        server-dir: /
